'use client';

import { Button } from '@/components/ui/button';

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (ch) => (({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as Record<string, string>)[ch] ?? ch));
}

function generateReportHTML(topic: string, papers: any[], artifacts: any[]): string {
  const insightArtifact = artifacts.find((a: any) => a.agentType === 'contradiction-finder');
  const trendArtifact = artifacts.find((a: any) => a.agentType === 'trend-mapper');

  const contradictions: any[] = insightArtifact?.data?.contradictions ?? [];
  const emergingTopics: any[] = trendArtifact?.data?.emergingTopics ?? [];

  const insightsHtml = contradictions.length > 0
    ? `<h2>Key Contradictions &amp; Debates</h2>
      <ul>
        ${contradictions.slice(0, 5).map((c: any) => `<li><strong>${escapeHtml(c.claim ?? c.topic ?? '')}</strong>: ${escapeHtml((c.description ?? c.detail ?? '').slice(0, 200))}</li>`).join('')}
      </ul>`
    : '';

  const topicsHtml = emergingTopics.length > 0
    ? `<h2>Emerging Topics</h2>
      <ul>
        ${emergingTopics.slice(0, 5).map((t: any) => `<li><strong>${escapeHtml(t.topic ?? '')}</strong>${t.paperCount ? ` — ${t.paperCount} papers` : ''}</li>`).join('')}
      </ul>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(topic)} — AI Research Lab Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 820px; margin: 2rem auto; padding: 0 1.25rem; color: #1a1a1a; line-height: 1.6; }
    h1, h2 { color: #1e40af; }
    h1 { font-size: 1.75rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.15rem; margin-top: 2rem; border-bottom: 2px solid #e0e7ff; padding-bottom: 0.25rem; }
    .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 2rem; }
    .paper { margin: 1rem 0; padding: 1rem 1.25rem; border-left: 3px solid #6366f1; background: #f5f5ff; border-radius: 0 6px 6px 0; }
    .paper h3 { margin: 0 0 0.35rem; font-size: 0.95rem; color: #1e293b; }
    .paper .authors { color: #475569; font-size: 0.8rem; margin-bottom: 0.5rem; }
    .paper .abstract { color: #334155; font-size: 0.82rem; }
    ul li { margin-bottom: 0.5rem; }
    footer { margin-top: 3rem; font-size: 0.75rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 1rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(topic)} — Research Report</h1>
  <p class="meta">Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} · <strong>${papers.length}</strong> papers</p>
  ${insightsHtml}
  ${topicsHtml}
  <h2>Papers</h2>
  ${papers.slice(0, 50).map((p: any) => {
    const title = escapeHtml(typeof p.title === 'string' ? p.title : 'Untitled');
    const authors = Array.isArray(p.authors)
      ? escapeHtml(p.authors.map((a: any) => (typeof a === 'string' ? a : (a?.name ?? ''))).filter(Boolean).join(', '))
      : '';
    const date = p.publishedAt ? new Date(p.publishedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'short' }) : '';
    const abstract = escapeHtml((typeof p.abstract === 'string' ? p.abstract : '').slice(0, 400));
    return `
  <div class="paper">
    <h3>${title}</h3>
    <p class="authors">${[authors, date].filter(Boolean).join(' · ')}</p>
    ${abstract ? `<p class="abstract">${abstract}${(p.abstract ?? '').length > 400 ? '…' : ''}</p>` : ''}
  </div>`;
  }).join('')}
  <footer>Generated by AI Research Lab · ${window.location.origin}</footer>
</body>
</html>`;
}

interface ExportButtonProps {
  topic?: string;
  papers?: any[];
  artifacts?: any[];
}

export function ExportButton({ topic = 'Research', papers = [], artifacts = [] }: ExportButtonProps) {
  const handleExport = () => {
    const html = generateReportHTML(topic, papers, artifacts);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-research-lab-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={handleExport}
      className="h-10 w-10"
      title="Export report"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
        <polyline points="16 6 12 2 8 6" />
        <line x1="12" y1="2" x2="12" y2="15" />
      </svg>
    </Button>
  );
}
